[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[tool.poetry]
name = "Python Project Template"
version = "1.0"
description = "A template for Python Projects."
license = "MIT"
authors = ["Xithrius <xithrius@gmail.com>"]

[tool.poetry.dependencies]
python = "3.9.5"

[tool.poetry.dev-dependencies]
flake8 = "~=3.9.2"
flake8-annotations = "~=2.6.2"
flake8-bugbear = "~=21.4.3"
flake8-docstrings = "~=1.6.0"
flake8-import-order = "~=0.18.1"
flake8-string-format = "~=0.3.0"
flake8-tidy-imports = "~=4.5.0"
flake8-todo = "~=0.7"
pep8-naming = "~=0.11.1"
pre-commit = "~=2.13.0"
python-dotenv = "^0.18.0"
taskipy = "^1.8.1"

[tool.taskipy.tasks]
start = ""
lint = "pre-commit run --all-files"
precommit = "pre-commit install"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
